<?php
    echo "Variable Declaration (C)\n";
    echo "Default Functions (C)\n";
    echo "Conditional Statements (C)\n";
    echo "Loops(C)\n";
    echo "Arrays (C)\n";
    echo "Magic Constants(C)\n";
    echo "Functions (C)\n";
    echo "Classes (C)\n";
    echo "Inheritance\n";
    echo "Polymorphism (C)\n";
    echo "Abstract Classes\n";
    echo "Interfaces\n";
    echo "Namespaces\n";
    echo "Exceptions\n";
    echo "Advanced Data Structure - HashMap, Set, Tree, Heap, BST\n";
    echo "POST GET DELETE PUT\n";
    echo "API Building\n";
    echo "Database Connectivity\n";
    echo "PHP and SQL Query\n";
    echo "File Handling\n";
    echo "File Uploading\n";
    echo "Cookies Handling\n";
    echo "Sessions Handling\n";
    echo "Sending Emails\n";
    echo "Form Handling\n";
    echo "Regular Expressions\n";
    echo "Error Handling\n";
    echo "Date and Time\n";
    echo "PHP and MySQL\n";
    echo "PHP and JSON\n";
    echo "PHP and CURL\n";
?>